GET http://localhost:9000/mahangs/c12ec8ea-7d41-8bf9-bba4-6bda3c0f0b3d/socats

###search
GET http://localhost:9000/mahangs?tenhang_like=q

###search
GET http://localhost:9000/mahangs?q=08

###pagination
GET http://localhost:9000/mahangs?_sort=tenhang&_order=desc&_page=2&_limit=2

###
GET http://localhost:9000/socats?ngaycat_gte=11/07/2021&ngaycat_lte=12/07/2021

###delete
DELETE http://localhost:9000/socats/b6729e1f-20ef-58d5-d370-e7b1721a5556


